# Generated by Django 5.1.5 on 2025-03-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_middle_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
